/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:21.462250 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 4, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:21.462250', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:24.273933 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 8, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:24.273933', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:26.899308 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 12, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:26.899308', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:29.622247 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 16, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:29.622247', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:32.328091 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 20, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:32.328091', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:34.975645 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 24, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:34.975645', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:37.618546 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 28, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:37.618546', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:40.240739 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 32, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:40.240739', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:42.949796 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 36, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:42.949796', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:45.620908 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 40, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:45.620908', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:48.273240 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 44, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:48.273240', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:50.978826 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 48, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:50.978826', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:53.649781 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 52, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:53.649781', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:56.330424 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 56, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:56.330424', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:05:58.927494 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 60, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:05:58.927494', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:06:01.578151 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 64, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:06:01.578151', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:06:04.204130 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 68, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:06:04.204130', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:06:06.855430 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 72, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:06:06.855430', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:06:09.533580 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 76, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:06:09.533580', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/backends/cuda.py:142: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cudnn).
  warnings.warn(
/home/jkgpu/miniconda3/lib/python3.8/site-packages/chainer/_environment_check.py:70: UserWarning: 
--------------------------------------------------------------------------------
CuPy (cupy) version 8.0.0 may not be compatible with this version of Chainer.
Please consider installing the supported version by running:
  $ pip install 'cupy>=6.3.0,<7.0.0'

See the following page for more details:
  https://docs-cupy.chainer.org/en/latest/install.html
--------------------------------------------------------------------------------

  warnings.warn(msg.format(
CuPy installation found, continuing using GPU acceleration.
having the CPUs {8, 9, 10, 11} available.
Started basinhopping at 2020-12-25 07:06:12.204735 UTC, with
command line arguments = {'path': '/home/jkgpu/HVQE/data/kagome/periodic/own_graph/opl/infidelity/3x2', 'n_par': 80, 'par_multiplicity': 9, 'n_iter': 0, 'cost_fn': 'infidelity', 'temperature': 1.0, 'stepsize': 1.0, 'init_par': None, 'dump_interval': None}
runtime variables =  {'GPU': True, 'date_start': '2020-12-25 07:06:12.204735', 'complete_graph': [(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5), (1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4), (1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17), (0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'init_layer': [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)], 'layers': [[(0, 6), (2, 8), (4, 10), (12, 9), (14, 11), (16, 7), (15, 1), (17, 3), (13, 5)], [(1, 6), (3, 8), (5, 10), (7, 12), (9, 14), (11, 16), (13, 0), (15, 2), (17, 4)], [(1, 2), (3, 4), (5, 0), (8, 12), (10, 14), (6, 16), (7, 13), (9, 15), (11, 17)], [(0, 1), (2, 3), (4, 5), (6, 7), (8, 9), (10, 11), (12, 13), (14, 15), (16, 17)]], 'n': 18}
Traceback (most recent call last):
  File "/home/jkgpu/HVQE/HVQE.py", line 78, in <module>
    vqe_out=_HVQE.run_VQE(cmd_args,run_args,init_reg)
  File "/home/jkgpu/HVQE/_HVQE.py", line 160, in run_VQE
    sol=scipy.optimize.basinhopping(calc_cost,vqe_out.init_par,stepsize=cmd_args.stepsize,minimizer_kwargs={'jac':True, 'options':{'gtol':0.5e-05}},niter=cmd_args.n_iter,interval=25,callback=callback,T=cmd_args.temperature)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 678, in basinhopping
    bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 72, in __init__
    minres = minimizer(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_basinhopping.py", line 284, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 612, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 1101, in _minimize_bfgs
    sf = _prepare_scalar_function(fun, x0, jac, args=args, epsilon=eps,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 76, in __init__
    self._update_fun()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 166, in _update_fun
    self._update_fun_impl()
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 73, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 70, in fun_wrapped
    return fun(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/jkgpu/miniconda3/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/jkgpu/HVQE/_HVQE.py", line 104, in calc_cost
    cost=infidelity_from_parameters(init_reg,run_args.layers,run_args,run_args.n,cmd_args.par_multiplicity,parameters)
  File "/home/jkgpu/HVQE/_HVQE.py", line 74, in infidelity_from_parameters
    for i in range(len(parameters)):
TypeError: object of type 'int' has no len()
